config/routes.rb
RvucounterRails::Application.routes.draw do

  root to: 'charges#new'

  resources :charges
  get 'codes/:code_category', to: 'codes#for_category', :defaults => { :format => :json }, :as => 'for_category'
  resources :codes



end

app/models/charge.rb
class Charge < ActiveRecord::Base


  validates :pan,
            numericality: { only_integer: true, greater_than_or_equal_to: 0, allow_nil: false }


end

app/models/code.rb
class Code < ActiveRecord::Base

  CATEGORIES = ['clinic','hospital','inter','general','ep']

  validates :number,
            numericality: { only_integer: true, greater_than_or_equal_to: 0, allow_nil: false }

  validates :rvu,
            numericality: { only_integer: true, greater_than_or_equal_to: 0, allow_nil: false }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
    @charge = Charge.new
    @codes = Code.all
  end

  def show
    @charge = Charge.find(params[:id])
  end

  def index
    @charges = Charge.all
  end

  def create
    @charge = Charge.new(charge_params)
    if @charge.save
      redirect_to @charge, notice: "Charge was successfully created."
    else
      render action: 'new', notice: "There was an error"
    end
  end

  private

  def charge_params
    params.require(:charge).permit(:pan, :code_category, :code_number, :code_rvu, :descriptor)
  end

end

app/controllers/codes_controller.rb
class CodesController < ApplicationController

  def index
    @code = Code.new
    @allCodes = Code.all
  end

  def create
    @code = Code.new(code_params)

    if @code.save
      redirect_to codes_path, notice: "Code was successfully created."
    else
      render action: 'index'
    end
  end

  def edit
    @code = Code.find(params[:id])
  end

  def update
    @code = Code.find(params[:id])    

    if @code.update_attributes(code_params)
      redirect_to codes_path, notice: "Code was successfully updated."
    else
      render action: 'index'
    end
  end

  def destroy
    @code = Code.find(params[:id])
    @code.destroy
    redirect_to codes_path
  end

  def for_category
    @codes_for_category = Code.where("category = ?", params[:code_category])

    respond_to do |format|
      format.json { render json: @codes_for_category.to_json(:only => [:category, :number, :rvu]) }
    end
  end
  
  private

  def code_params
    params.require(:code).permit(:number, :category, :rvu)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # create text with an icon to the left for bootstrap menus and buttons
  def text_with_icon(text, icon_name)
    raw("#{icon(icon_name)} #{text}")
  end

  # generate a standard bootstrap glyphicon
  def icon(name)
    content_tag(:span, nil, class: "glyphicon glyphicon-#{name}")
  end

  # action name to use for the primary submit button on scaffold-created CRUD forms
  def btn_action_prefix
    case action_name
      when 'show', 'create'
        'Create'
      when 'edit', 'update'
        'Update'
      else
        nil
    end
  end

  # bootstrap icon name to use for the primary submit button on scaffold-created forms
  def action_icon_name
    case action_name
      when 'show', 'create'
        'plus'
      when 'edit', 'update'
        'edit'
      else
        nil
    end
  end

  def alert_class(alert_type)
    alert_type = {
      alert: 'danger',
      notice: 'info'
    }.with_indifferent_access.fetch(alert_type, alert_type.to_s)
    "alert-#{alert_type}"
  end

end

app/views/charges/index.html.slim
table.table
  thead
    th PAN
    th Code Type
    th Code #
    th Code RVU
    th Descriptor
    th Time
  - @charges.each do |c|
    tbody
      tr
        td= number_with_precision(c.pan, precision: 0)
        td= c.code_category
        td= c.code_number
        td= c.code_rvu
        td= c.descriptor
        td= c.created_at.to_formatted_s(:long)

  =link_to 'New charge', new_charge_path, class: 'btn btn-default'

app/views/charges/new.html.slim
h1 RVU Counter

#container
  - unless @charge.errors.empty?
    h3= @charge.errors.messages
  #barcode
    label Scan your barcode:
    input id="barcode_upload" type="file" accept="image/*;capture=camera"
    canvas width="20" height="20" id="picture"
  = simple_form_for(@charge, html: { class: "charge-form form-horizontal #{@charge.errors.empty? ? '' : 'charge-errors'}" }, wrapper: :horizontal_form, \
    wrapper_mappings: { \
      check_boxes: :horizontal_radio_and_checkboxes, \
      radio_buttons: :horizontal_radio_and_checkboxes, \
      file: :horizontal_file_input, \
      boolean: :horizontal_boolean \
    }) do |f|
    = f.error_notification
    = f.input :pan, as: :string
    = f.input :code_category, collection: Code::CATEGORIES, :input_html => { :data =>  { :dynamic_selectable_url => for_category_path(':code_category'), :dynamic_selectable_target => '#charge_code_number_rvu' } }

    table.table.table-hover
      th Code #
      th RVU
      tbody#charge_code_number_rvu.row
    = f.input :descriptor

    = f.button :submit

/script type="application/javascript" src="/assets/JOB.js"
/script type="application/javascript" src="/assets/job_upload.js"
= javascript_include_tag "JOB"
= javascript_include_tag "job_upload"

app/views/charges/show.html.slim
table.table
  thead
    th PAN
    th Code Type
    th Code #
    th Code RVU
    th Descriptor
    th Time
  tbody
    tr
      td= number_with_precision(@charge.pan, precision: 0)
      td= @charge.code_category
      td= @charge.code_number
      td= @charge.code_rvu
      td= @charge.descriptor
      td= @charge.created_at.to_formatted_s(:long)

=link_to 'New charge', new_charge_path, class: 'btn btn-default'

app/views/codes/_form.html.slim
= simple_form_for(@code, \
          wrapper_mappings: { \
            check_boxes: :horizontal_radio_and_checkboxes, \
            radio_buttons: :horizontal_radio_and_checkboxes \
          }) do |f|
  = f.error_notification
  = f.input :number, wrapper_html: { class: 'col-md-2' }
  = f.input :category, collection: Code::CATEGORIES, wrapper_html: { class: 'col-md-4' }
  = f.input :rvu, wrapper_html: { class: 'col-md-2' }
  /= f.input :choices, as: :check_boxes, \
  /   collection: ["Option one is this and that—be sure to include why it's great", "Option two can be something else and selecting it will deselect option one"]
  = f.button :submit

app/views/codes/edit.html.slim
#container.row
  = render :partial => "form", :code => @code

app/views/codes/index.html.slim
#container.row
 = render :partial => "form", :code => @code

.row
  - unless @allCodes.nil?
    table.code-table.table.table-hover
      thead
        tr
          th Code #
          th Category
          th RVU
          th
          th
      - @allCodes.each do |c|
        tr
          td= c.number
          td= c.category
          td= c.rvu
          td.col-md-1= link_to 'Edit', edit_code_path(c), class: 'btn btn-default btn-mini'
          td.col-md-1= link_to 'Destroy', code_path(c), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-mini btn-danger'

app/views/codes/show.html.slim
= render :partial => "form", :code => @code

app/views/layouts/application.html.slim
doctype 5
html
  head
    title RVUcounter
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = javascript_include_tag 'exif'
    javascript:
      var decoderWorkerUrl = "#{asset_url('DecoderWorker.js')}";
    = csrf_meta_tag
    meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no'

  body id=(controller.controller_name) class=(controller.action_name)
    .wrapper
      nav.navbar.navbar-default.navbar-fixed-top role='navigation'
        .container
          .navbar-header
            button.navbar-toggle.collapsed type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
              span.sr-only Toggle navigation/span
              span.icon-bar
              span.icon-bar
              span.icon-bar
            a class="navbar-brand" href="#" RVUCounter

          /!-- Collect the nav links, forms, and other content for toggling --
          #bs-example-navbar-collapse-1.collapse.navbar-collapse
            ul.nav.navbar-nav
              li
                a href="#{codes_path}" Codes
              li.dropdown.active
                a.dropdown-toggle href="#" data-toggle="dropdown" role="button" aria-expanded="false"
                  | Charges
                  span.caret
                ul.dropdown-menu role="menu"
                  li
                    a href="#{new_charge_path}" New Charge
                  li
                    a href="#{charges_path}" All Charges

      .container
        - flash.each do |name, msg|
          .alert.alert-dismissable class=alert_class(name)
            button.close type='button' data-dismiss='alert' aria-hidden='true' &times;
            =raw(msg)
        = yield

    footer
      .container
        p &copy; #{Date.current.year} All rights reserved.